# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
  
displayName: 'Setup build environment'

- script: |
    git clone https://github.com/akhilnarang/scripts.git
    cd scripts
    ls
    ./setup/android_build_env.sh
  displayName: 'Run a multi-line script'
